director_uuid: d459f71f-f22e-4880-8538-10ce0b817c20

name: postgres

jobs:
- instances: 1
  name: postgres_z1
  networks:
  - name: postgres1
    static_ips:
    - 10.244.4.4
  persistent_disk: 4096
  resource_pool: postgres_z1
  templates:
  - name: postgres
    release: postgres
  update: {}

networks:
- name: postgres1
  subnets:
  - cloud_properties:
      name: random
    gateway: 10.244.4.1
    range: 10.244.4.0/24
    reserved:
    - 10.244.4.2-10.244.4.3
    - 10.244.4.30-10.244.4.254
    static:
    - 10.244.4.4
  type: manual

compilation:
  cloud_properties: {}
  network: postgres1
  reuse_compilation_vms: true
  workers: 3

releases:
- name: postgres
  version: latest

resource_pools:
- cloud_properties: {}
  name: postgres_z1
  network: postgres1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000

properties:
  databases:
    additional_config: null
    address: 10.244.4.4
    collect_statement_statistics: true
    databases:
    - citext: true
      name: ccdb
      tag: cc
    - citext: true
      name: uaadb
      tag: uaa
    - citext: false
      name: diego
      tag: diego
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: admin
      tag: admin
    - name: uaaadmin
      password: admin
      tag: admin
    - name: diego
      password: admin
      tag: admin
